"""Pure decision engine for credit limit evaluation - NO I/O operations"""

from src.credit_decision.models import (
    DECISION_APPROVE,
    DECISION_DECLINE,
    DECISION_REFER,
    REASON_EXPLANATIONS,
    REASON_LIMIT_CAPPED_BY_GRADE,
    REASON_PAST_DUE_DATA_MISSING,
    REASON_PAST_DUE_OVER_60,
    REASON_RISK_DATA_MISSING,
    REASON_RISK_GRADE_HIGH,
    REASON_RISK_GRADE_MEDIUM,
    RISK_GRADE_MAX_LIMITS,
    BuyerRiskProfile,
    CreditDecisionRequest,
    CreditDecisionResponse,
)


def evaluate_decision(
    request: CreditDecisionRequest,
    risk_profile: BuyerRiskProfile,
    decision_id: str,
    timestamp: str,
) -> CreditDecisionResponse:
    """
    Pure function to evaluate credit limit decision based on risk profile.

    This function implements all 7 decision rules in fixed order for deterministic results.
    No I/O operations, no AWS SDK calls, no random values, no side effects.

    Decision Rules (evaluated in order):
    1. Risk grade D or E → DECLINE
    2. Risk grade C → REFER
    3. Risk grade A/B + past due over 60 → REFER
    4. Risk grade A + no past due → APPROVE (up to 1M, cap if needed)
    5. Risk grade B + no past due → APPROVE (up to 500K, cap if needed)
    6. Missing risk grade → REFER
    7. Missing past due data → REFER

    Args:
        request: The credit decision request from underwriter
        risk_profile: Buyer risk assessment data
        decision_id: Unique identifier for this decision (generated by caller)
        timestamp: ISO 8601 UTC timestamp (generated by caller)

    Returns:
        CreditDecisionResponse with decision, approved limit, reason codes, and explanations
    """
    reason_codes: list[str] = []
    decision: str
    approved_limit: int

    # Rule 1: Risk grade D or E → DECLINE
    if risk_profile.riskGrade in ["D", "E"]:
        decision = DECISION_DECLINE
        approved_limit = 0
        reason_codes.append(REASON_RISK_GRADE_HIGH)

    # Rule 2: Risk grade C → REFER
    elif risk_profile.riskGrade == "C":
        decision = DECISION_REFER
        approved_limit = 0
        reason_codes.append(REASON_RISK_GRADE_MEDIUM)

    # Rule 6: Missing risk grade → REFER
    elif risk_profile.riskGrade is None:
        decision = DECISION_REFER
        approved_limit = 0
        reason_codes.append(REASON_RISK_DATA_MISSING)

    # Rule 7: Missing past due data → REFER
    elif risk_profile.pastDueOver60 is None:
        decision = DECISION_REFER
        approved_limit = 0
        reason_codes.append(REASON_PAST_DUE_DATA_MISSING)

    # Rule 3: Risk grade A/B + past due over 60 → REFER
    elif risk_profile.riskGrade in ["A", "B"] and risk_profile.pastDueOver60 is True:
        decision = DECISION_REFER
        approved_limit = 0
        reason_codes.append(REASON_PAST_DUE_OVER_60)

    # Rules 4 & 5: Risk grade A or B + no past due → APPROVE (with capping)
    elif risk_profile.riskGrade in ["A", "B"] and risk_profile.pastDueOver60 is False:
        decision = DECISION_APPROVE
        max_limit = RISK_GRADE_MAX_LIMITS[risk_profile.riskGrade]

        if request.requestedLimit <= max_limit:
            approved_limit = request.requestedLimit
        else:
            approved_limit = max_limit
            reason_codes.append(REASON_LIMIT_CAPPED_BY_GRADE)

    # Fallback: Unknown risk grade value → REFER (treat as missing data)
    else:
        decision = DECISION_REFER
        approved_limit = 0
        reason_codes.append(REASON_RISK_DATA_MISSING)

    # Generate explanations for all reason codes
    explanations = [REASON_EXPLANATIONS[code] for code in reason_codes]

    return CreditDecisionResponse(
        decisionId=decision_id,
        decision=decision,
        approvedLimit=approved_limit,
        currency=request.currency,
        reasonCodes=reason_codes,
        explanations=explanations,
        timestamp=timestamp,
    )
